/* eslint-disable  @typescript-eslint/no-explicit-any */

// Generated by dts-gen initially, version "solc": "^0.8.21"

declare module "solc" {
  export function compile(inputRaw: string, readCallback?: any): any;
}
