// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: issuer/v1/issuer.proto

package issuer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClaimTypeEnum int32

const (
	ClaimTypeEnum_CLAIM_TYPE_ENUM_UNSPECIFIED ClaimTypeEnum = 0
	ClaimTypeEnum_CLAIM_TYPE_ENUM_SCALAR      ClaimTypeEnum = 1
	ClaimTypeEnum_CLAIM_TYPE_ENUM_PROPERTY    ClaimTypeEnum = 2
	ClaimTypeEnum_CLAIM_TYPE_ENUM_BOOLEAN     ClaimTypeEnum = 3
)

// Enum value maps for ClaimTypeEnum.
var (
	ClaimTypeEnum_name = map[int32]string{
		0: "CLAIM_TYPE_ENUM_UNSPECIFIED",
		1: "CLAIM_TYPE_ENUM_SCALAR",
		2: "CLAIM_TYPE_ENUM_PROPERTY",
		3: "CLAIM_TYPE_ENUM_BOOLEAN",
	}
	ClaimTypeEnum_value = map[string]int32{
		"CLAIM_TYPE_ENUM_UNSPECIFIED": 0,
		"CLAIM_TYPE_ENUM_SCALAR":      1,
		"CLAIM_TYPE_ENUM_PROPERTY":    2,
		"CLAIM_TYPE_ENUM_BOOLEAN":     3,
	}
)

func (x ClaimTypeEnum) Enum() *ClaimTypeEnum {
	p := new(ClaimTypeEnum)
	*p = x
	return p
}

func (x ClaimTypeEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClaimTypeEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_issuer_v1_issuer_proto_enumTypes[0].Descriptor()
}

func (ClaimTypeEnum) Type() protoreflect.EnumType {
	return &file_issuer_v1_issuer_proto_enumTypes[0]
}

func (x ClaimTypeEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClaimTypeEnum.Descriptor instead.
func (ClaimTypeEnum) EnumDescriptor() ([]byte, []int) {
	return file_issuer_v1_issuer_proto_rawDescGZIP(), []int{0}
}

type PropHashEnum int32

const (
	PropHashEnum_PROP_HASH_ENUM_UNSPECIFIED PropHashEnum = 0
	PropHashEnum_PROP_HASH_ENUM_POSEIDON    PropHashEnum = 1
	PropHashEnum_PROP_HASH_ENUM_KECCAK256   PropHashEnum = 2
	PropHashEnum_PROP_HASH_ENUM_CUSTOM      PropHashEnum = 3
)

// Enum value maps for PropHashEnum.
var (
	PropHashEnum_name = map[int32]string{
		0: "PROP_HASH_ENUM_UNSPECIFIED",
		1: "PROP_HASH_ENUM_POSEIDON",
		2: "PROP_HASH_ENUM_KECCAK256",
		3: "PROP_HASH_ENUM_CUSTOM",
	}
	PropHashEnum_value = map[string]int32{
		"PROP_HASH_ENUM_UNSPECIFIED": 0,
		"PROP_HASH_ENUM_POSEIDON":    1,
		"PROP_HASH_ENUM_KECCAK256":   2,
		"PROP_HASH_ENUM_CUSTOM":      3,
	}
)

func (x PropHashEnum) Enum() *PropHashEnum {
	p := new(PropHashEnum)
	*p = x
	return p
}

func (x PropHashEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PropHashEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_issuer_v1_issuer_proto_enumTypes[1].Descriptor()
}

func (PropHashEnum) Type() protoreflect.EnumType {
	return &file_issuer_v1_issuer_proto_enumTypes[1]
}

func (x PropHashEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PropHashEnum.Descriptor instead.
func (PropHashEnum) EnumDescriptor() ([]byte, []int) {
	return file_issuer_v1_issuer_proto_rawDescGZIP(), []int{1}
}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_issuer_v1_issuer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_issuer_v1_issuer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_issuer_v1_issuer_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_issuer_v1_issuer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_issuer_v1_issuer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_issuer_v1_issuer_proto_rawDescGZIP(), []int{1}
}

type ClaimType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//	*ClaimType_ScalarType_
	//	*ClaimType_PropertyType_
	//	*ClaimType_BooleanType_
	Type isClaimType_Type `protobuf_oneof:"type"`
}

func (x *ClaimType) Reset() {
	*x = ClaimType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_issuer_v1_issuer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimType) ProtoMessage() {}

func (x *ClaimType) ProtoReflect() protoreflect.Message {
	mi := &file_issuer_v1_issuer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimType.ProtoReflect.Descriptor instead.
func (*ClaimType) Descriptor() ([]byte, []int) {
	return file_issuer_v1_issuer_proto_rawDescGZIP(), []int{2}
}

func (m *ClaimType) GetType() isClaimType_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *ClaimType) GetScalarType() *ClaimType_ScalarType {
	if x, ok := x.GetType().(*ClaimType_ScalarType_); ok {
		return x.ScalarType
	}
	return nil
}

func (x *ClaimType) GetPropertyType() *ClaimType_PropertyType {
	if x, ok := x.GetType().(*ClaimType_PropertyType_); ok {
		return x.PropertyType
	}
	return nil
}

func (x *ClaimType) GetBooleanType() *ClaimType_BooleanType {
	if x, ok := x.GetType().(*ClaimType_BooleanType_); ok {
		return x.BooleanType
	}
	return nil
}

type isClaimType_Type interface {
	isClaimType_Type()
}

type ClaimType_ScalarType_ struct {
	ScalarType *ClaimType_ScalarType `protobuf:"bytes,1,opt,name=scalar_type,json=scalarType,proto3,oneof"`
}

type ClaimType_PropertyType_ struct {
	PropertyType *ClaimType_PropertyType `protobuf:"bytes,2,opt,name=property_type,json=propertyType,proto3,oneof"`
}

type ClaimType_BooleanType_ struct {
	BooleanType *ClaimType_BooleanType `protobuf:"bytes,3,opt,name=boolean_type,json=booleanType,proto3,oneof"`
}

func (*ClaimType_ScalarType_) isClaimType_Type() {}

func (*ClaimType_PropertyType_) isClaimType_Type() {}

func (*ClaimType_BooleanType_) isClaimType_Type() {}

type ClaimDef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ClaimType *ClaimType `protobuf:"bytes,2,opt,name=claim_type,json=claimType,proto3" json:"claim_type,omitempty"`
}

func (x *ClaimDef) Reset() {
	*x = ClaimDef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_issuer_v1_issuer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimDef) ProtoMessage() {}

func (x *ClaimDef) ProtoReflect() protoreflect.Message {
	mi := &file_issuer_v1_issuer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimDef.ProtoReflect.Descriptor instead.
func (*ClaimDef) Descriptor() ([]byte, []int) {
	return file_issuer_v1_issuer_proto_rawDescGZIP(), []int{3}
}

func (x *ClaimDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClaimDef) GetClaimType() *ClaimType {
	if x != nil {
		return x.ClaimType
	}
	return nil
}

type CredType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Claims    []*ClaimDef `protobuf:"bytes,1,rep,name=claims,proto3" json:"claims,omitempty"`
	Revocable *int64      `protobuf:"varint,2,opt,name=revocable,proto3,oneof" json:"revocable,omitempty"`
	TypeId    string      `protobuf:"bytes,3,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
}

func (x *CredType) Reset() {
	*x = CredType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_issuer_v1_issuer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CredType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredType) ProtoMessage() {}

func (x *CredType) ProtoReflect() protoreflect.Message {
	mi := &file_issuer_v1_issuer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredType.ProtoReflect.Descriptor instead.
func (*CredType) Descriptor() ([]byte, []int) {
	return file_issuer_v1_issuer_proto_rawDescGZIP(), []int{4}
}

func (x *CredType) GetClaims() []*ClaimDef {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *CredType) GetRevocable() int64 {
	if x != nil && x.Revocable != nil {
		return *x.Revocable
	}
	return 0
}

func (x *CredType) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

type ClaimValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//	*ClaimValue_ScalarValue_
	//	*ClaimValue_PropertyValue_
	//	*ClaimValue_BoolValue_
	Value isClaimValue_Value `protobuf_oneof:"value"`
}

func (x *ClaimValue) Reset() {
	*x = ClaimValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_issuer_v1_issuer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimValue) ProtoMessage() {}

func (x *ClaimValue) ProtoReflect() protoreflect.Message {
	mi := &file_issuer_v1_issuer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimValue.ProtoReflect.Descriptor instead.
func (*ClaimValue) Descriptor() ([]byte, []int) {
	return file_issuer_v1_issuer_proto_rawDescGZIP(), []int{5}
}

func (m *ClaimValue) GetValue() isClaimValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *ClaimValue) GetScalarValue() *ClaimValue_ScalarValue {
	if x, ok := x.GetValue().(*ClaimValue_ScalarValue_); ok {
		return x.ScalarValue
	}
	return nil
}

func (x *ClaimValue) GetPropertyValue() *ClaimValue_PropertyValue {
	if x, ok := x.GetValue().(*ClaimValue_PropertyValue_); ok {
		return x.PropertyValue
	}
	return nil
}

func (x *ClaimValue) GetBoolValue() *ClaimValue_BoolValue {
	if x, ok := x.GetValue().(*ClaimValue_BoolValue_); ok {
		return x.BoolValue
	}
	return nil
}

type isClaimValue_Value interface {
	isClaimValue_Value()
}

type ClaimValue_ScalarValue_ struct {
	ScalarValue *ClaimValue_ScalarValue `protobuf:"bytes,1,opt,name=scalar_value,json=scalarValue,proto3,oneof"`
}

type ClaimValue_PropertyValue_ struct {
	PropertyValue *ClaimValue_PropertyValue `protobuf:"bytes,2,opt,name=property_value,json=propertyValue,proto3,oneof"`
}

type ClaimValue_BoolValue_ struct {
	BoolValue *ClaimValue_BoolValue `protobuf:"bytes,3,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*ClaimValue_ScalarValue_) isClaimValue_Value() {}

func (*ClaimValue_PropertyValue_) isClaimValue_Value() {}

func (*ClaimValue_BoolValue_) isClaimValue_Value() {}

type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Type    string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Context string `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	Id      string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_issuer_v1_issuer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_issuer_v1_issuer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_issuer_v1_issuer_proto_rawDescGZIP(), []int{6}
}

func (x *Header) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Header) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Header) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *Header) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Body struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tp     *CredType     `protobuf:"bytes,1,opt,name=tp,proto3" json:"tp,omitempty"`
	Values []*ClaimValue `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *Body) Reset() {
	*x = Body{}
	if protoimpl.UnsafeEnabled {
		mi := &file_issuer_v1_issuer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Body) ProtoMessage() {}

func (x *Body) ProtoReflect() protoreflect.Message {
	mi := &file_issuer_v1_issuer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Body.ProtoReflect.Descriptor instead.
func (*Body) Descriptor() ([]byte, []int) {
	return file_issuer_v1_issuer_proto_rawDescGZIP(), []int{7}
}

func (x *Body) GetTp() *CredType {
	if x != nil {
		return x.Tp
	}
	return nil
}

func (x *Body) GetValues() []*ClaimValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type AttachmentSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attachments map[string]string `protobuf:"bytes,1,rep,name=attachments,proto3" json:"attachments,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *AttachmentSet) Reset() {
	*x = AttachmentSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_issuer_v1_issuer_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachmentSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentSet) ProtoMessage() {}

func (x *AttachmentSet) ProtoReflect() protoreflect.Message {
	mi := &file_issuer_v1_issuer_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentSet.ProtoReflect.Descriptor instead.
func (*AttachmentSet) Descriptor() ([]byte, []int) {
	return file_issuer_v1_issuer_proto_rawDescGZIP(), []int{8}
}

func (x *AttachmentSet) GetAttachments() map[string]string {
	if x != nil {
		return x.Attachments
	}
	return nil
}

type GenerateSignedCredentialRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header             *Header        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body               *Body          `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Attachments        *AttachmentSet `protobuf:"bytes,3,opt,name=attachments,proto3" json:"attachments,omitempty"`
	ChainId            uint64         `protobuf:"varint,4,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	IdentityCommitment string         `protobuf:"bytes,5,opt,name=identity_commitment,json=identityCommitment,proto3" json:"identity_commitment,omitempty"`
	ExpiredAt          string         `protobuf:"bytes,6,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
}

func (x *GenerateSignedCredentialRequest) Reset() {
	*x = GenerateSignedCredentialRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_issuer_v1_issuer_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateSignedCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSignedCredentialRequest) ProtoMessage() {}

func (x *GenerateSignedCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_issuer_v1_issuer_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSignedCredentialRequest.ProtoReflect.Descriptor instead.
func (*GenerateSignedCredentialRequest) Descriptor() ([]byte, []int) {
	return file_issuer_v1_issuer_proto_rawDescGZIP(), []int{9}
}

func (x *GenerateSignedCredentialRequest) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GenerateSignedCredentialRequest) GetBody() *Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *GenerateSignedCredentialRequest) GetAttachments() *AttachmentSet {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *GenerateSignedCredentialRequest) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GenerateSignedCredentialRequest) GetIdentityCommitment() string {
	if x != nil {
		return x.IdentityCommitment
	}
	return ""
}

func (x *GenerateSignedCredentialRequest) GetExpiredAt() string {
	if x != nil {
		return x.ExpiredAt
	}
	return ""
}

type GenerateSignedCredentialResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SignedCred string `protobuf:"bytes,1,opt,name=signed_cred,json=signedCred,proto3" json:"signed_cred,omitempty"`
}

func (x *GenerateSignedCredentialResponse) Reset() {
	*x = GenerateSignedCredentialResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_issuer_v1_issuer_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateSignedCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSignedCredentialResponse) ProtoMessage() {}

func (x *GenerateSignedCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_issuer_v1_issuer_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSignedCredentialResponse.ProtoReflect.Descriptor instead.
func (*GenerateSignedCredentialResponse) Descriptor() ([]byte, []int) {
	return file_issuer_v1_issuer_proto_rawDescGZIP(), []int{10}
}

func (x *GenerateSignedCredentialResponse) GetSignedCred() string {
	if x != nil {
		return x.SignedCred
	}
	return ""
}

type ClaimType_ScalarType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width int64 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
}

func (x *ClaimType_ScalarType) Reset() {
	*x = ClaimType_ScalarType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_issuer_v1_issuer_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimType_ScalarType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimType_ScalarType) ProtoMessage() {}

func (x *ClaimType_ScalarType) ProtoReflect() protoreflect.Message {
	mi := &file_issuer_v1_issuer_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimType_ScalarType.ProtoReflect.Descriptor instead.
func (*ClaimType_ScalarType) Descriptor() ([]byte, []int) {
	return file_issuer_v1_issuer_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ClaimType_ScalarType) GetWidth() int64 {
	if x != nil {
		return x.Width
	}
	return 0
}

type ClaimType_PropertyType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width         int64        `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	HashAlgorithm PropHashEnum `protobuf:"varint,2,opt,name=hash_algorithm,json=hashAlgorithm,proto3,enum=issuer.v1.PropHashEnum" json:"hash_algorithm,omitempty"`
	NEqualChecks  *int64       `protobuf:"varint,3,opt,name=n_equal_checks,json=nEqualChecks,proto3,oneof" json:"n_equal_checks,omitempty"`
}

func (x *ClaimType_PropertyType) Reset() {
	*x = ClaimType_PropertyType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_issuer_v1_issuer_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimType_PropertyType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimType_PropertyType) ProtoMessage() {}

func (x *ClaimType_PropertyType) ProtoReflect() protoreflect.Message {
	mi := &file_issuer_v1_issuer_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimType_PropertyType.ProtoReflect.Descriptor instead.
func (*ClaimType_PropertyType) Descriptor() ([]byte, []int) {
	return file_issuer_v1_issuer_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ClaimType_PropertyType) GetWidth() int64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ClaimType_PropertyType) GetHashAlgorithm() PropHashEnum {
	if x != nil {
		return x.HashAlgorithm
	}
	return PropHashEnum_PROP_HASH_ENUM_UNSPECIFIED
}

func (x *ClaimType_PropertyType) GetNEqualChecks() int64 {
	if x != nil && x.NEqualChecks != nil {
		return *x.NEqualChecks
	}
	return 0
}

type ClaimType_BooleanType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value bool `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ClaimType_BooleanType) Reset() {
	*x = ClaimType_BooleanType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_issuer_v1_issuer_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimType_BooleanType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimType_BooleanType) ProtoMessage() {}

func (x *ClaimType_BooleanType) ProtoReflect() protoreflect.Message {
	mi := &file_issuer_v1_issuer_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimType_BooleanType.ProtoReflect.Descriptor instead.
func (*ClaimType_BooleanType) Descriptor() ([]byte, []int) {
	return file_issuer_v1_issuer_proto_rawDescGZIP(), []int{2, 2}
}

func (x *ClaimType_BooleanType) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type ClaimValue_ScalarValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ClaimValue_ScalarValue) Reset() {
	*x = ClaimValue_ScalarValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_issuer_v1_issuer_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimValue_ScalarValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimValue_ScalarValue) ProtoMessage() {}

func (x *ClaimValue_ScalarValue) ProtoReflect() protoreflect.Message {
	mi := &file_issuer_v1_issuer_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimValue_ScalarValue.ProtoReflect.Descriptor instead.
func (*ClaimValue_ScalarValue) Descriptor() ([]byte, []int) {
	return file_issuer_v1_issuer_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ClaimValue_ScalarValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ClaimValue_PropertyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string  `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Hash  *string `protobuf:"bytes,2,opt,name=hash,proto3,oneof" json:"hash,omitempty"`
}

func (x *ClaimValue_PropertyValue) Reset() {
	*x = ClaimValue_PropertyValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_issuer_v1_issuer_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimValue_PropertyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimValue_PropertyValue) ProtoMessage() {}

func (x *ClaimValue_PropertyValue) ProtoReflect() protoreflect.Message {
	mi := &file_issuer_v1_issuer_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimValue_PropertyValue.ProtoReflect.Descriptor instead.
func (*ClaimValue_PropertyValue) Descriptor() ([]byte, []int) {
	return file_issuer_v1_issuer_proto_rawDescGZIP(), []int{5, 1}
}

func (x *ClaimValue_PropertyValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ClaimValue_PropertyValue) GetHash() string {
	if x != nil && x.Hash != nil {
		return *x.Hash
	}
	return ""
}

type ClaimValue_BoolValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value bool `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ClaimValue_BoolValue) Reset() {
	*x = ClaimValue_BoolValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_issuer_v1_issuer_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimValue_BoolValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimValue_BoolValue) ProtoMessage() {}

func (x *ClaimValue_BoolValue) ProtoReflect() protoreflect.Message {
	mi := &file_issuer_v1_issuer_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimValue_BoolValue.ProtoReflect.Descriptor instead.
func (*ClaimValue_BoolValue) Descriptor() ([]byte, []int) {
	return file_issuer_v1_issuer_proto_rawDescGZIP(), []int{5, 2}
}

func (x *ClaimValue_BoolValue) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

var File_issuer_v1_issuer_proto protoreflect.FileDescriptor

var file_issuer_v1_issuer_proto_rawDesc = []byte{
	0x0a, 0x16, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x73, 0x73, 0x75,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x22, 0x0d, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0xd6, 0x03, 0x0a, 0x09, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x42, 0x0a, 0x0b, 0x73, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x53, 0x63, 0x61, 0x6c,
	0x61, 0x72, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x73, 0x63, 0x61, 0x6c, 0x61, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x48, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x69, 0x73,
	0x73, 0x75, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x54, 0x79, 0x70,
	0x65, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00,
	0x52, 0x0c, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x45,
	0x0a, 0x0c, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x65,
	0x61, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x61,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x1a, 0x22, 0x0a, 0x0a, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x1a, 0xa2, 0x01, 0x0a, 0x0c, 0x50, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69,
	0x64, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68,
	0x12, 0x3e, 0x0a, 0x0e, 0x68, 0x61, 0x73, 0x68, 0x5f, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74,
	0x68, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x69, 0x73, 0x73, 0x75, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x48, 0x61, 0x73, 0x68, 0x45, 0x6e, 0x75,
	0x6d, 0x52, 0x0d, 0x68, 0x61, 0x73, 0x68, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d,
	0x12, 0x29, 0x0a, 0x0e, 0x6e, 0x5f, 0x65, 0x71, 0x75, 0x61, 0x6c, 0x5f, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x0c, 0x6e, 0x45, 0x71, 0x75,
	0x61, 0x6c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x88, 0x01, 0x01, 0x42, 0x11, 0x0a, 0x0f, 0x5f,
	0x6e, 0x5f, 0x65, 0x71, 0x75, 0x61, 0x6c, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x1a, 0x23,
	0x0a, 0x0b, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x53, 0x0a, 0x08, 0x43,
	0x6c, 0x61, 0x69, 0x6d, 0x44, 0x65, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x0a, 0x63,
	0x6c, 0x61, 0x69, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x61, 0x69,
	0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x54, 0x79, 0x70, 0x65,
	0x22, 0x81, 0x01, 0x0a, 0x08, 0x43, 0x72, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2b, 0x0a,
	0x06, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x44,
	0x65, 0x66, 0x52, 0x06, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x12, 0x21, 0x0a, 0x09, 0x72, 0x65,
	0x76, 0x6f, 0x63, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52,
	0x09, 0x72, 0x65, 0x76, 0x6f, 0x63, 0x61, 0x62, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a,
	0x07, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x74, 0x79, 0x70, 0x65, 0x49, 0x64, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x72, 0x65, 0x76, 0x6f, 0x63,
	0x61, 0x62, 0x6c, 0x65, 0x22, 0xfe, 0x02, 0x0a, 0x0a, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x46, 0x0a, 0x0c, 0x73, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x69, 0x73, 0x73, 0x75,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x2e, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x0b,
	0x73, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x4c, 0x0a, 0x0e, 0x70,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6c, 0x61, 0x69, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65,
	0x72, 0x74, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x40, 0x0a, 0x0a, 0x62, 0x6f, 0x6f,
	0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00,
	0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x23, 0x0a, 0x0b, 0x53,
	0x63, 0x61, 0x6c, 0x61, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x1a, 0x47, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x17, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x88, 0x01, 0x01,
	0x42, 0x07, 0x0a, 0x05, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x1a, 0x21, 0x0a, 0x09, 0x42, 0x6f, 0x6f,
	0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x07, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x60, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x5a, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x12,
	0x23, 0x0a, 0x02, 0x74, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x69, 0x73,
	0x73, 0x75, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x02, 0x74, 0x70, 0x12, 0x2d, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x22, 0x9c, 0x01, 0x0a, 0x0d, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x65, 0x74, 0x12, 0x4b, 0x0a, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x69, 0x73, 0x73,
	0x75, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e,
	0x74, 0x53, 0x65, 0x74, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x1a, 0x3e, 0x0a, 0x10, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x98, 0x02, 0x0a, 0x1f, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53,
	0x69, 0x67, 0x6e, 0x65, 0x64, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x23, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6f, 0x64, 0x79,
	0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x3a, 0x0a, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69, 0x73,
	0x73, 0x75, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x65, 0x74, 0x52, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x2f, 0x0a,
	0x13, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x41, 0x74, 0x22, 0x43, 0x0a,
	0x20, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x43,
	0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x5f, 0x63, 0x72, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x43, 0x72,
	0x65, 0x64, 0x2a, 0x87, 0x01, 0x0a, 0x0d, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x54, 0x79, 0x70, 0x65,
	0x45, 0x6e, 0x75, 0x6d, 0x12, 0x1f, 0x0a, 0x1b, 0x43, 0x4c, 0x41, 0x49, 0x4d, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x43, 0x4c, 0x41, 0x49, 0x4d, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x53, 0x43, 0x41, 0x4c, 0x41, 0x52, 0x10,
	0x01, 0x12, 0x1c, 0x0a, 0x18, 0x43, 0x4c, 0x41, 0x49, 0x4d, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x50, 0x52, 0x4f, 0x50, 0x45, 0x52, 0x54, 0x59, 0x10, 0x02, 0x12,
	0x1b, 0x0a, 0x17, 0x43, 0x4c, 0x41, 0x49, 0x4d, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x45, 0x4e,
	0x55, 0x4d, 0x5f, 0x42, 0x4f, 0x4f, 0x4c, 0x45, 0x41, 0x4e, 0x10, 0x03, 0x2a, 0x84, 0x01, 0x0a,
	0x0c, 0x50, 0x72, 0x6f, 0x70, 0x48, 0x61, 0x73, 0x68, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x1e, 0x0a,
	0x1a, 0x50, 0x52, 0x4f, 0x50, 0x5f, 0x48, 0x41, 0x53, 0x48, 0x5f, 0x45, 0x4e, 0x55, 0x4d, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1b, 0x0a,
	0x17, 0x50, 0x52, 0x4f, 0x50, 0x5f, 0x48, 0x41, 0x53, 0x48, 0x5f, 0x45, 0x4e, 0x55, 0x4d, 0x5f,
	0x50, 0x4f, 0x53, 0x45, 0x49, 0x44, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x1c, 0x0a, 0x18, 0x50, 0x52,
	0x4f, 0x50, 0x5f, 0x48, 0x41, 0x53, 0x48, 0x5f, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x4b, 0x45, 0x43,
	0x43, 0x41, 0x4b, 0x32, 0x35, 0x36, 0x10, 0x02, 0x12, 0x19, 0x0a, 0x15, 0x50, 0x52, 0x4f, 0x50,
	0x5f, 0x48, 0x41, 0x53, 0x48, 0x5f, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x43, 0x55, 0x53, 0x54, 0x4f,
	0x4d, 0x10, 0x03, 0x32, 0xc1, 0x01, 0x0a, 0x0d, 0x49, 0x73, 0x73, 0x75, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x2e,
	0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x75, 0x0a, 0x18, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x6e,
	0x65, 0x64, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x2a, 0x2e, 0x69,
	0x73, 0x73, 0x75, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x69, 0x73, 0x73, 0x75, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67,
	0x6e, 0x65, 0x64, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0xa5, 0x01, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x2e,
	0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x42, 0x0b, 0x49, 0x73, 0x73, 0x75, 0x65,
	0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x61, 0x6c, 0x78, 0x65, 0x2f, 0x67, 0x61, 0x6c, 0x78, 0x65,
	0x2d, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x67, 0x6f, 0x3b, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0xa2, 0x02, 0x03, 0x49,
	0x58, 0x58, 0xaa, 0x02, 0x09, 0x49, 0x73, 0x73, 0x75, 0x65, 0x72, 0x2e, 0x56, 0x31, 0xca, 0x02,
	0x09, 0x49, 0x73, 0x73, 0x75, 0x65, 0x72, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x15, 0x49, 0x73, 0x73,
	0x75, 0x65, 0x72, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0xea, 0x02, 0x0a, 0x49, 0x73, 0x73, 0x75, 0x65, 0x72, 0x3a, 0x3a, 0x56, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_issuer_v1_issuer_proto_rawDescOnce sync.Once
	file_issuer_v1_issuer_proto_rawDescData = file_issuer_v1_issuer_proto_rawDesc
)

func file_issuer_v1_issuer_proto_rawDescGZIP() []byte {
	file_issuer_v1_issuer_proto_rawDescOnce.Do(func() {
		file_issuer_v1_issuer_proto_rawDescData = protoimpl.X.CompressGZIP(file_issuer_v1_issuer_proto_rawDescData)
	})
	return file_issuer_v1_issuer_proto_rawDescData
}

var file_issuer_v1_issuer_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_issuer_v1_issuer_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_issuer_v1_issuer_proto_goTypes = []interface{}{
	(ClaimTypeEnum)(0),                       // 0: issuer.v1.ClaimTypeEnum
	(PropHashEnum)(0),                        // 1: issuer.v1.PropHashEnum
	(*PingRequest)(nil),                      // 2: issuer.v1.PingRequest
	(*PingResponse)(nil),                     // 3: issuer.v1.PingResponse
	(*ClaimType)(nil),                        // 4: issuer.v1.ClaimType
	(*ClaimDef)(nil),                         // 5: issuer.v1.ClaimDef
	(*CredType)(nil),                         // 6: issuer.v1.CredType
	(*ClaimValue)(nil),                       // 7: issuer.v1.ClaimValue
	(*Header)(nil),                           // 8: issuer.v1.Header
	(*Body)(nil),                             // 9: issuer.v1.Body
	(*AttachmentSet)(nil),                    // 10: issuer.v1.AttachmentSet
	(*GenerateSignedCredentialRequest)(nil),  // 11: issuer.v1.GenerateSignedCredentialRequest
	(*GenerateSignedCredentialResponse)(nil), // 12: issuer.v1.GenerateSignedCredentialResponse
	(*ClaimType_ScalarType)(nil),             // 13: issuer.v1.ClaimType.ScalarType
	(*ClaimType_PropertyType)(nil),           // 14: issuer.v1.ClaimType.PropertyType
	(*ClaimType_BooleanType)(nil),            // 15: issuer.v1.ClaimType.BooleanType
	(*ClaimValue_ScalarValue)(nil),           // 16: issuer.v1.ClaimValue.ScalarValue
	(*ClaimValue_PropertyValue)(nil),         // 17: issuer.v1.ClaimValue.PropertyValue
	(*ClaimValue_BoolValue)(nil),             // 18: issuer.v1.ClaimValue.BoolValue
	nil,                                      // 19: issuer.v1.AttachmentSet.AttachmentsEntry
}
var file_issuer_v1_issuer_proto_depIdxs = []int32{
	13, // 0: issuer.v1.ClaimType.scalar_type:type_name -> issuer.v1.ClaimType.ScalarType
	14, // 1: issuer.v1.ClaimType.property_type:type_name -> issuer.v1.ClaimType.PropertyType
	15, // 2: issuer.v1.ClaimType.boolean_type:type_name -> issuer.v1.ClaimType.BooleanType
	4,  // 3: issuer.v1.ClaimDef.claim_type:type_name -> issuer.v1.ClaimType
	5,  // 4: issuer.v1.CredType.claims:type_name -> issuer.v1.ClaimDef
	16, // 5: issuer.v1.ClaimValue.scalar_value:type_name -> issuer.v1.ClaimValue.ScalarValue
	17, // 6: issuer.v1.ClaimValue.property_value:type_name -> issuer.v1.ClaimValue.PropertyValue
	18, // 7: issuer.v1.ClaimValue.bool_value:type_name -> issuer.v1.ClaimValue.BoolValue
	6,  // 8: issuer.v1.Body.tp:type_name -> issuer.v1.CredType
	7,  // 9: issuer.v1.Body.values:type_name -> issuer.v1.ClaimValue
	19, // 10: issuer.v1.AttachmentSet.attachments:type_name -> issuer.v1.AttachmentSet.AttachmentsEntry
	8,  // 11: issuer.v1.GenerateSignedCredentialRequest.header:type_name -> issuer.v1.Header
	9,  // 12: issuer.v1.GenerateSignedCredentialRequest.body:type_name -> issuer.v1.Body
	10, // 13: issuer.v1.GenerateSignedCredentialRequest.attachments:type_name -> issuer.v1.AttachmentSet
	1,  // 14: issuer.v1.ClaimType.PropertyType.hash_algorithm:type_name -> issuer.v1.PropHashEnum
	2,  // 15: issuer.v1.IssuerService.Ping:input_type -> issuer.v1.PingRequest
	11, // 16: issuer.v1.IssuerService.GenerateSignedCredential:input_type -> issuer.v1.GenerateSignedCredentialRequest
	3,  // 17: issuer.v1.IssuerService.Ping:output_type -> issuer.v1.PingResponse
	12, // 18: issuer.v1.IssuerService.GenerateSignedCredential:output_type -> issuer.v1.GenerateSignedCredentialResponse
	17, // [17:19] is the sub-list for method output_type
	15, // [15:17] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_issuer_v1_issuer_proto_init() }
func file_issuer_v1_issuer_proto_init() {
	if File_issuer_v1_issuer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_issuer_v1_issuer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_issuer_v1_issuer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_issuer_v1_issuer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_issuer_v1_issuer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimDef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_issuer_v1_issuer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CredType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_issuer_v1_issuer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_issuer_v1_issuer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_issuer_v1_issuer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Body); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_issuer_v1_issuer_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttachmentSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_issuer_v1_issuer_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateSignedCredentialRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_issuer_v1_issuer_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateSignedCredentialResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_issuer_v1_issuer_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimType_ScalarType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_issuer_v1_issuer_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimType_PropertyType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_issuer_v1_issuer_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimType_BooleanType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_issuer_v1_issuer_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimValue_ScalarValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_issuer_v1_issuer_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimValue_PropertyValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_issuer_v1_issuer_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimValue_BoolValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_issuer_v1_issuer_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*ClaimType_ScalarType_)(nil),
		(*ClaimType_PropertyType_)(nil),
		(*ClaimType_BooleanType_)(nil),
	}
	file_issuer_v1_issuer_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_issuer_v1_issuer_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*ClaimValue_ScalarValue_)(nil),
		(*ClaimValue_PropertyValue_)(nil),
		(*ClaimValue_BoolValue_)(nil),
	}
	file_issuer_v1_issuer_proto_msgTypes[12].OneofWrappers = []interface{}{}
	file_issuer_v1_issuer_proto_msgTypes[15].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_issuer_v1_issuer_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_issuer_v1_issuer_proto_goTypes,
		DependencyIndexes: file_issuer_v1_issuer_proto_depIdxs,
		EnumInfos:         file_issuer_v1_issuer_proto_enumTypes,
		MessageInfos:      file_issuer_v1_issuer_proto_msgTypes,
	}.Build()
	File_issuer_v1_issuer_proto = out.File
	file_issuer_v1_issuer_proto_rawDesc = nil
	file_issuer_v1_issuer_proto_goTypes = nil
	file_issuer_v1_issuer_proto_depIdxs = nil
}
